// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoeShop.Infrastructure;

#nullable disable

namespace ShoeShop.Infrastructure.Migrations
{
    [DbContext(typeof(ShoeShopContext))]
    [Migration("20251004150209_ConfigurePriceAndSeedData")]
    partial class ConfigurePriceAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShoeShop.Infrastructure.Entities.Shoe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Shoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nike",
                            Name = "Air Max 90",
                            Price = 120.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Adidas",
                            Name = "Stan Smith",
                            Price = 80.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Converse",
                            Name = "Chuck Taylor All Star",
                            Price = 65.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Vans",
                            Name = "Old Skool",
                            Price = 75.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Nike",
                            Name = "Air Jordan 1",
                            Price = 170.00m,
                            Stock = 12
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
